public with sharing class Calculator {
    public Calculator() {

    }
    public Integer add(Integer a, Integer b) {
        return a + b;
    }
    public Integer subtract(Integer a, Integer b) {
        return a - b;
    }
    public Integer multiply(Integer a, Integer b) {
        return a * b;
    }
    public Integer divide(Integer a, Integer b) {
        return a / b; 
        //comit the code
    }
   
}