/****************************************************************************
 * version    name                     Date            Description
 ***************************************************************************** 
 * v1.0        Developer1             2024-06-01      Add Method Implimentation
 *
 ***********************************.************************************/

public with sharing class Calculator {
    public Calculator() {
        
    }
   Public integer add(Integer a, Integer b) {
        return a + b;
    }
    
    
    }   
