/****************************
*Class :Calculator
*Author : Rohit Thakur
*Date : 2024-06-17
*Description : This class is used to perform basic arithmetic operations like addition, subtraction, multiplication and
************************************/

public with sharing class Calculator {
    public Calculator() {

    }
  
   public Integer subtract(Integer a, Integer b){
       return a-b;
   }
  
   
}